name: Modificar Contingut Github
on:
  push:
    branches:
      - main
jobs:
  ModificaRepositoriGithubAmbGithubActions_ElTeuNom:
    runs-on: ubuntu-latest
    permissions: # para poder modificar el contenido del repositorio
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Modifica fitxer md
        run: |
          echo -e "- ${{ github.actor }} modifica el repo ${{ github.repository }} : "`date`"\n" >> README.md

      - name: Modifica fitxer index.html
        run: |
          git pull origin main
          sed -i 's|</body>|<!-- Contenido modificado por Github Actions -->\n</body>|' index.html
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md index.html
          git commit -m "AÃ±adido contenido a README.md y modificado index.html"
          git push
