name: Modificar Contingut Github
on:
  push:
    branches:
      - main
jobs:
  ModificaRepositoriGithubAmbGithubActions_marc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Modifica fitxer md
        run: |
          echo "- ${{ github.actor }} ha modificat el repo ${{ github.repository }} : $(date)" >> README.md

      - name: Modifica div en index.html
        run: |
          git pull origin main
          sed -i '/<ul>/a \ \ \ \ \ \ <li>Contingut modificat per Github Actions</li>' index.html
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md index.html
          git commit -m "Actualitzat README.md i modificat div en index.html"
          git push
